### ISSUE TITLE
what we can used for custom connector, Module SDK or Client SDK?

### ISSUE THREAD

**Issue by sagarpatel07** [attivio/sdk#4]

**Comment by antpanman** [comment]
If you wish to run the connector from an Attivio node, you should start with the module archetype. If you wish to write an external application to push documents in via the IngestAPI, you would start with the client archetype.

**Comment by sagarpatel07** [comment]
Thanks for reply. I have one more question - what class we required to extend for custom connector which provide start method ? or is there any example available for custom connector using Module SDK ?

**Comment by antpanman** [comment]
At this time, we're in the middle of transitioning between the legacy SDK and this one here on GitHub. Not all features and functionality are yet accessible via the new SDK. Some of the classes required for authoring connectors (a.k.a. scanners) fall into this category.

That being said, if you have access to https://answers.attivio.com/display/extranet55/Creating+Custom+Scanners, it walks through creating a custom scanner. For any of the imports that do not work using the new SDK, you can pull in additional dependencies by editing your Maven POM to reference a local installation of Attivio.

For example, you could add a property such as...
```
  <properties>
    ...
    <attivio.home>c:/unscanned/aie_5.5.0</attivio.home>
  </properties>
```

Then pull in a dependency such as...

```
    <dependency>
      <groupId>com.attivio.platform.core</groupId>
      <artifactId>api</artifactId>
      <version>${attivio.version}</version>
      <scope>system</scope>
      <systemPath>${attivio.home}/lib/aie-core-api.jar</systemPath>
    </dependency>
```

We will be adding a Connector SDK later this year to make this process easier, but until then, you can make use of non-SDK classes using this method.
